### ISSUE TITLE
Setup Mapit

### ISSUE THREAD

**Issue by pasindud** [CodeLanka/mapit#2]
Can someone pull from https://github.com/pasindud/mapit and try to add some data.

@iamchathu @agentmilindu @tdevinda @pamuditha  @rhperera

**Comment by iamchathu** [comment]
@pasindud from this repo or yours ?

**Comment by pasindud** [comment]
Pull from mine to this

**Comment by iamchathu** [comment]
@pasindud 

Pushed your repo to gh-pages branch

**Comment by pasindud** [comment]
👍
